// Ledger — n8n Code node "Build report HTML".
// Turns the report Markdown + deal header into a standalone HTML document for
// HTML->PDF (Gotenberg). Outputs json (carried forward) + binary 'index.html'.
// Run Once for All Items. Adjust the two $('...') reads to your node names.

const score = $('Score risk').first().json;                 // { analysis_id, patch }
const reportText = $('OpenRouter report').first().json.choices[0].message.content;
const patch = score.patch;

const esc = (s) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const inline = (t) => t.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>").replace(/\*([^*]+)\*/g, "<em>$1</em>");

function mdToHtml(src) {
  const lines = esc(src).split(/\r?\n/);
  let html = "", inList = false;
  const closeList = () => { if (inList) { html += "</ul>"; inList = false; } };
  for (const ln of lines) {
    const t = ln.trim();
    if (!t) { closeList(); continue; }
    let m;
    if ((m = /^###\s+(.*)/.exec(t))) { closeList(); html += `<h3>${inline(m[1])}</h3>`; }
    else if ((m = /^##\s+(.*)/.exec(t))) { closeList(); html += `<h2>${inline(m[1])}</h2>`; }
    else if ((m = /^#\s+(.*)/.exec(t))) { closeList(); html += `<h1>${inline(m[1])}</h1>`; }
    else if ((m = /^[-*]\s+(.*)/.exec(t))) { if (!inList) { html += "<ul>"; inList = true; } html += `<li>${inline(m[1])}</li>`; }
    else { closeList(); html += `<p>${inline(t)}</p>`; }
  }
  closeList();
  return html;
}

const recColors = { pursue: "#15803d", pursue_with_conditions: "#b45309", pass: "#b91c1c" };
const rec = patch.recommendation || "pursue";

const html = `<!doctype html><html><head><meta charset="utf-8"><style>
  body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1a1a1a;margin:48px;line-height:1.55;font-size:13px;}
  .head{border-bottom:2px solid #ececec;padding-bottom:16px;margin-bottom:24px;}
  .title{font-size:24px;font-weight:700;}
  .muted{color:#8a8a8a;font-size:11px;}
  .rec{display:inline-block;margin-top:10px;padding:4px 12px;border-radius:999px;color:#fff;font-weight:600;font-size:12px;background:${recColors[rec] || "#555"};}
  h1{font-size:18px;margin:22px 0 8px;} h2{font-size:15px;margin:18px 0 6px;}
  h3{font-size:11px;margin:14px 0 4px;color:#666;text-transform:uppercase;letter-spacing:.06em;}
  ul{margin:8px 0 8px 18px;} li{margin:3px 0;} p{margin:6px 0;}
</style></head><body>
  <div class="head">
    <div class="title">${esc(patch.property_name || "Screening report")}</div>
    <div class="muted">${esc(patch.property_subtype || "")}${patch.location ? " · " + esc(patch.location) : ""}</div>
    <span class="rec">${esc(rec.replace(/_/g, " "))}</span>
  </div>
  ${mdToHtml(reportText)}
  <p class="muted" style="margin-top:32px;border-top:1px solid #ececec;padding-top:12px;">
    Generated by Ledger. Verify all figures against the source OM. Not investment advice.
  </p>
</body></html>`;

return [{
  json: { analysis_id: score.analysis_id, patch, report_text: reportText },
  binary: {
    "index.html": {
      data: Buffer.from(html, "utf-8").toString("base64"),
      mimeType: "text/html",
      fileName: "index.html",
    },
  },
}];
